### ISSUE TITLE
Fehler bei Mapimport und Inkompatibilität mit Python 3.7

### ISSUE THREAD

**Issue by cederikhoefs** [RandInt83/AI-Challenge#19]
TODO: new type classes implementieren, um Kompatibilität mit Python 2.7 und 3.0 zu gewährleisten.
Beim Map-Import passieren böse Dinge, scheinbar werden Farben manchmal falsch interpretiert.

**Comment by BendiXB** [comment]
Bei welchem Bild treten die Lesefehler auf?
Ich habe beim Testen keine Fehler festgestellt, solange richtigen Farbwerte gewählt sind.

**Comment by cederikhoefs** [comment]
Molff hat eins, ich lasse ihn das mal hier reinschicken.
